name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache yarn cache
      uses: actions/cache@v2
      env:
        cache-name: cache-yarn-cache
      with:
        path: ${{ yarn cache dir }}
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run build
      run: yarn build

    - name: Run tests
      run: yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI

    - name: Run end-to-end tests
      run: yarn e2e --protractor-config=e2e/protractor-ci.conf.js
